---
deployment:
  tasks:
    - export DEPLOYPATH=/home/uygpuazs/public_html/
    - /bin/cp index.html $DEPLOYPATH
    - /bin/cp robots.txt $DEPLOYPATH
    - /bin/cp sitemap.xml $DEPLOYPATH
    - /bin/cp .htaccess $DEPLOYPATH
    - /bin/cp -R assets $DEPLOYPATH
    - /bin/cp -R api $DEPLOYPATH
    - /bin/cp -R cache $DEPLOYPATH
